//
// Created by musht on 21.09.2022.
//

#ifndef DATABASELABSE_SCHEME_H
#define DATABASELABSE_SCHEME_H

#include <string>
#include <ostream>

using str = std::string;
using ost = std::ostream;
using sst = std::stringstream;

// represents student entry
class Student{
public:
    int id;
    str name, surname, patronymic;
    Student(const str &s, bool withId);
    friend ost &operator<<(ost &os, const Student &v);
    str toString() const;
};

// variant entry
class Variant {
public:
    int id;
    str path;
    Variant(const str &s, bool withId);
    friend ost &operator<<(ost &os, const Variant &v);
    str toString() const;
};

// generated by db
class Distribution {
public:
    int id, var;
    Distribution(const str &s, bool withId);
    Distribution(int studId, int varId);
    friend ost &operator<<(ost &os, const Distribution &d);
    str toString() const;
};

#endif //DATABASELABSE_SCHEME_H
